import { api } from '@/services/api';

const BASE_URL = '/formData';

export const getAllFreight = async () => api.get(`${BASE_URL}`);

export const postFreight = async ({
  name,
  collectCity,
  collectDate,
  deliveryCity,
  deliveryDate,
  product,
  species,
  weight,
  volume,
  weightCuban,
  sizeCubic,
  length,
  height,
  freightPrice,
  paymentForm,
  comments,
  advancePrice,
  valueCalculation,
  radioValueLocalizacao,
  radioValueTipoCarga,
  radioValueLona,
  radioValueRastreador,
  unitMeasurement,
  radioValueValor,
  radioValuePedagio,
  radioPacoteEscolhido,
  veiculos,
  carrocerias,
  idResponsible,
}) =>
  api.post(`${BASE_URL}`, {
    name,
    collectCity,
    collectDate,
    deliveryCity,
    deliveryDate,
    product,
    species,
    weight,
    volume,
    weightCuban,
    sizeCubic,
    length,
    height,
    freightPrice,
    paymentForm,
    comments,
    advancePrice,
    valueCalculation,
    radioValueLocalizacao,
    radioValueTipoCarga,
    radioValueLona,
    radioValueRastreador,
    unitMeasurement,
    radioValueValor,
    radioValuePedagio,
    radioPacoteEscolhido,
    veiculos,
    carrocerias,
    idResponsible,
  });
