export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-anatonelly-bg bg-center bg-no-repeat bg-cover bg-fixed bg-gray-900 overflow-hidden  w-full h-full relative -z-50">
        {children}
      </body>
    </html>
  );
}
